Feature/view actions
humio/cli pull request #53
Opened 2020-11-05 09:42 UTC by mahlunar

## Context

This PR relates to the following issue: https://github.com/humio/humio-operator/issues/207 - CRD for HumioViews

The View API needs additional functions before we can add a CRD for managing views. This is the first PR on that journey. 

This is my first open source PR so bear with me 

## Overview of changes

1. Added the following operations to Views
    * Create
    * Update Connections
    * Update Description
    * Delete

2. Updated the CLI with the new operations as well.

3. Fixed a bug in Delete repository which returned an error after successfully deleting a repository due to a graphQL query error.

2020-11-05 10:23 UTC, danielamkaer requested changes
LGTM. Tested the commands and found no issues.

2020-11-05 10:23 UTC, danielamkaer commented on cmd/humioctl/views_create.go
> +			fmt.Println(fmt.Sprintf("Sucessfully created view %s", viewName))
```suggestion
			fmt.Println(fmt.Sprintf("Successfully created view %s", viewName))
```

2020-11-05 10:23 UTC, danielamkaer commented on cmd/humioctl/views_create.go
> +		Use:   "create",
```suggestion
		Use:   "create <view-name>",
```

2020-11-05 10:23 UTC, danielamkaer commented on cmd/humioctl/views_delete.go
> +			fmt.Printf("Reason: '%s'", reason)
```suggestion
			fmt.Printf("Deleting view %s with reason %q\n", view, reason)
```

2020-11-05 11:06 UTC, mahlunar commented
Thanks for the quick reaction. I have committed the suggested changes.

2020-11-05 11:37 UTC, danielamkaer approved these changes
Great. Thanks!

2020-11-05 11:38 UTC, merged

2020-11-06 08:18 UTC, mahlunar commented
Thanks. 🚀  Quick question. Would it be possible to get a new release of the CLI? We would need it to complete https://github.com/humio/humio-operator/issues/207

2020-11-06 08:31 UTC, danielamkaer commented
Sure. Version 0.28.1 released. 🎉